services:
    app02:
        build: 
          args: 
              user: 'lucas-borges'
              uid: 1000 
          dockerfile: Dockerfile 
        container_name: app02
        environment:
          - DB_HOST=db02
          - DB_DATABASE=laravel02
          - DB_USERNAME=root
          - DB_PASSWORD=root
        volumes:
          - .:/var/www
        networks:
          - app-network-02
        depends_on:
          - db02
          - redis02

    nginx02:
        build: .docker/nginx
        container_name: nginx02
        restart: always
        tty: true
        ports:
          - "8080:80"
        volumes:
          - .:/var/www
        networks:
          - app-network-02
        depends_on:
          - app02
    
    queue02:
        build: 
            args: 
                user: 'lucas-borges'
                uid: 1000
            dockerfile: Dockerfile
        container_name: queue02    
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes: 
            - .:/var/www
        depends_on: 
            - redis02
        networks: 
            - app-network-02

    db02:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: db02
        restart: always
        tty: true
        ports:
          - "3306:3306"
        volumes:
          - ./.docker/dbdata:/var/lib/mysql
        environment:
          - MYSQL_DATABASE=laravel02
          - MYSQL_ROOT_PASSWORD=root
        networks:
          - app-network-02

    redis02:
        image: redis:alpine
        volumes:
          - ./.docker/volumes/redis:/data
        container_name: redis02
        ports:
          - 6379:6379
        networks:
          - app-network-02

networks:
    app-network-02:
        driver: bridge